services:
  nginx:
    container_name: mpc-proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    external: true
    name: mpc-network
