services:
  app:
    container_name: mpc-api-app
    build:
      context: .
    volumes:
      - /app/node_modules
      - ./db:/app/db
    depends_on:
      - db

  db:
    container_name: mpc-api-db
    image: postgres:latest
    restart: unless-stopped
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changemeonemoretime}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      #PGDATA: /data/postgres
    volumes:
      - ./data/:/var/lib/postgresql/data

  nginx:
    container_name: mpc-api
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

networks:
  default:
    external: true
    name: mpc-network
